# SVD decomposition with `scipy`

Import the required modules

In [1]:
import scipy.linalg as la
import numpy as np

Generate a random 5x4 matrix

In [2]:
A = np.random.rand(5,4)
A

array([[0.84278919, 0.53022638, 0.55696719, 0.33126265],
       [0.86907541, 0.84208138, 0.71709281, 0.49297653],
       [0.41496109, 0.2660531 , 0.98676047, 0.68166833],
       [0.51202357, 0.03628258, 0.70203112, 0.65293876],
       [0.37929017, 0.21801575, 0.30627792, 0.51569407]])

## `<numpy|scipy>.linalg.svd` 

Equivalent implementations:
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html



### Full SVD (`full_matrices = True` - default)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times m}, S \in \mathbb{R}^{m\times n}, V \in \mathbb{R}^{n\times n}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.


In [3]:
U, s, VT = np.linalg.svd(A)
#U, s, VT = la.svd(A)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 5)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [4]:
S = np.zeros(A.shape)
for i in range(len(s)):
    S[i, i] = s[i]
S

array([[2.52842492, 0.        , 0.        , 0.        ],
       [0.        , 0.72715521, 0.        , 0.        ],
       [0.        , 0.        , 0.28591845, 0.        ],
       [0.        , 0.        , 0.        , 0.21149482],
       [0.        , 0.        , 0.        , 0.        ]])

In [5]:
S = la.diagsvd(s, A.shape[0], A.shape[1])
S

array([[2.52842492, 0.        , 0.        , 0.        ],
       [0.        , 0.72715521, 0.        , 0.        ],
       [0.        , 0.        , 0.28591845, 0.        ],
       [0.        , 0.        , 0.        , 0.21149482],
       [0.        , 0.        , 0.        , 0.        ]])

Reconstruct the matrix $A$

In [6]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))

err: 5.022617e-16


### Thin SVD (`full_matrices = False`)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times q}, S \in \mathbb{R}^{q\times q}, V \in \mathbb{R}^{n\times q}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.



In [7]:
del U, s, S, VT
U, s, VT = la.svd(A, full_matrices = False)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 4)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [8]:
S = np.diag(s)
S

array([[2.52842492, 0.        , 0.        , 0.        ],
       [0.        , 0.72715521, 0.        , 0.        ],
       [0.        , 0.        , 0.28591845, 0.        ],
       [0.        , 0.        , 0.        , 0.21149482]])

Reconstruct the matrix $A$

In [9]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))

err: 3.363531e-16
