# SciPy

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

## Introduction

The SciPy framework builds on top of the low-level NumPy framework for multidimensional arrays, and provides a large number of higher-level scientific algorithms. Some of the topics that SciPy covers are:

* Special functions ([scipy.special](http://docs.scipy.org/doc/scipy/reference/special.html))
* Integration ([scipy.integrate](http://docs.scipy.org/doc/scipy/reference/integrate.html))
* Optimization ([scipy.optimize](http://docs.scipy.org/doc/scipy/reference/optimize.html))
* Interpolation ([scipy.interpolate](http://docs.scipy.org/doc/scipy/reference/interpolate.html))
* Fourier Transforms ([scipy.fftpack](http://docs.scipy.org/doc/scipy/reference/fftpack.html))
* Signal Processing ([scipy.signal](http://docs.scipy.org/doc/scipy/reference/signal.html))
* Linear Algebra ([scipy.linalg](http://docs.scipy.org/doc/scipy/reference/linalg.html))
* Sparse Eigenvalue Problems ([scipy.sparse](http://docs.scipy.org/doc/scipy/reference/sparse.html))
* Statistics ([scipy.stats](http://docs.scipy.org/doc/scipy/reference/stats.html))
* Multi-dimensional image processing ([scipy.ndimage](http://docs.scipy.org/doc/scipy/reference/ndimage.html))
* File IO ([scipy.io](http://docs.scipy.org/doc/scipy/reference/io.html))

Each of these submodules provides a number of functions and classes that can be used to solve problems in their respective topics.

In this lecture we will look at how to use some of these subpackages.

To access the SciPy package in a Python program, we start by importing everything from the `scipy` module.

In [ ]:
from scipy import *

If we only need to use part of the SciPy framework we can selectively include only those modules we are interested in. For example, to include the linear algebra package under the name `la`, we can do:

In [ ]:
import scipy.linalg as la

## Linear algebra

The linear algebra module contains a lot of matrix related functions, including linear equation solving, eigenvalue solvers, matrix functions (for example matrix-exponentiation), a number of different decompositions (SVD, LU, cholesky), etc. 

Detailed documetation is available at: http://docs.scipy.org/doc/scipy/reference/linalg.html

Here we will look at how to use some of these functions:



### Linear equation systems

Linear equation systems on the matrix form

$A x = b$

where $A$ is a matrix and $x,b$ are vectors can be solved like:

In [1]:
import scipy.linalg as la
import numpy as np
from numpy import random

In [2]:
A = np.array([[1,2,3], [4,5,6], [6,8,9]])
b = np.array([6,15,23])

In [ ]:
A.transpose()

array([[1, 4, 6],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
A.T

array([[1, 4, 6],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
help(la.solve)

Help on function solve in module scipy.linalg.basic:

solve(a, b, sym_pos=False, lower=False, overwrite_a=False, overwrite_b=False, debug=None, check_finite=True, assume_a='gen', transposed=False)
    Solves the linear equation set ``a * x = b`` for the unknown ``x``
    for square ``a`` matrix.
    
    If the data matrix is known to be a particular type then supplying the
    corresponding string to ``assume_a`` key chooses the dedicated solver.
    The available options are
    
    ===================  ========
     generic matrix       'gen'
     symmetric            'sym'
     hermitian            'her'
     positive definite    'pos'
    ===================  ========
    
    If omitted, ``'gen'`` is the default structure.
    
    The datatype of the arrays define which solver is called regardless
    of the values. In other words, even when the complex array entries have
    precisely zero imaginary parts, the complex solver will be called based
    on the data type of the arr

In [ ]:
x = la.solve(A, b)
print(x)


[1. 1. 1.]


In [ ]:
# check
np.dot(A, x) - b

array([0., 0., 0.])

We can also do the same with

$A X = B$

where $A, B, X$ are matrices:

In [ ]:
A = random.rand(3,3)
B = random.rand(3,3)

In [ ]:
X = la.solve(A, B)

In [ ]:
X

array([[-0.04795782,  1.03937412, -0.25098415],
       [ 0.92752652,  0.47858424,  0.69493357],
       [ 0.17229905, -0.78208753,  0.67692863]])

In [ ]:
help(la.norm)

Help on function norm in module scipy.linalg.misc:

norm(a, ord=None, axis=None, keepdims=False, check_finite=True)
    Matrix or vector norm.
    
    This function is able to return one of seven different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    a : (M,) or (M, N) array_like
        Input array.  If `axis` is None, `a` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `a` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `a`
        is 1-D) or a 

In [ ]:
# check
la.norm(np.dot(A, X) - B)

2.1364582767275725e-16

### Eigenvalues and eigenvectors

The eigenvalue problem for a matrix $A$:

$\displaystyle A v_n = \lambda_n v_n$

where $v_n$ is the $n$th eigenvector and $\lambda_n$ is the $n$th eigenvalue.

To calculate eigenvalues of a matrix, use the `eigvals` and for calculating both eigenvalues and eigenvectors, use the function `eig`:

In [ ]:
help(la.eigvals)

Help on function eigvals in module scipy.linalg.decomp:

eigvals(a, b=None, overwrite_a=False, check_finite=True, homogeneous_eigvals=False)
    Compute eigenvalues from an ordinary or generalized eigenvalue problem.
    
    Find eigenvalues of a general matrix::
    
        a   vr[:,i] = w[i]        b   vr[:,i]
    
    Parameters
    ----------
    a : (M, M) array_like
        A complex or real matrix whose eigenvalues and eigenvectors
        will be computed.
    b : (M, M) array_like, optional
        Right-hand side matrix in a generalized eigenvalue problem.
        If omitted, identity matrix is assumed.
    overwrite_a : bool, optional
        Whether to overwrite data in a (may improve performance)
    check_finite : bool, optional
        Whether to check that the input matrices contain only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities
        or NaNs.
    h

In [ ]:
evals = la.eigvals(A)

In [ ]:
evals

array([1.7307039 +0.j       , 0.04604059+0.4423735j,
       0.04604059-0.4423735j])

In [ ]:
eigvv = la.eig(A)

In [ ]:
eigvv[0][0]

(1.7307038963632602+0j)

In [ ]:
eigvv[1][:,0]

array([-0.63750819+0.j, -0.32479824+0.j, -0.69863396+0.j])

The eigenvector corresponding to the $n$th eigenvalue (stored in the $n$th position of  `eigvv[0]`) is the $n$th *column* in `eigvv[1]`. To verify this, let's try mutiplying eigenvectors with the matrix and compare to the product of the eigenvector and the eigenvalue:

In [ ]:
n = 1

la.norm(np.dot(A, eigvv[1][:,n]) - eigvv[0][n] * eigvv[1][:,n])

There are also more specialized eigensolvers, like the `eigh` for Hermitian matrices. 

### Matrix operations

In [ ]:
# the matrix inverse
la.inv(A)

In [ ]:
# determinant.
la.det(A)

In [ ]:
# norms of various orders
la.norm(A, ord=2), la.norm(A, ord=np.inf)

In [ ]:
# condition number
np.linalg.cond(A)

In [ ]:
H=la.hilbert(10)
print(H)
np.linalg.cond(H)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333 0.07692308 0.07142857]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333 0.07692308 0.07142857 0.06666667]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308 0.07142857 0.06666667 0.0625    ]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  0.07142857 0.06666667 0.0625     0.05882353]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 0.0625     

16024416992541.715

In [ ]:
xtrue=np.array([1,1,1,1,1,1,1,1,1,1])
xtrue

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
bh=np.dot(H,xtrue.T)
bh

array([2.92896825, 2.01987734, 1.60321068, 1.34680042, 1.16822899,
       1.03489566, 0.93072899, 0.84669538, 0.77725094, 0.7187714 ])

In [ ]:
bh2=np.array([ 3.,  2.01987734,  1.60321068,  1.34680042,  1.16822899,
        1., 1.,  0.84669538,  0.77725094,  0.7187714 ])

In [ ]:
x1=la.solve(H,bh)
x2=la.solve(H,bh2)

In [ ]:
x1

array([1.        , 0.99999996, 1.00000087, 0.99999211, 1.00003756,
       0.99989682, 1.00016919, 0.99983655, 1.00008579, 0.99998114])

In [ ]:
x2

array([ 8.85723060e+05, -7.63363576e+07,  1.62228229e+09, -1.47187023e+10,
        7.00801059e+10, -1.92341747e+11,  3.15120079e+11, -3.04131498e+11,
        1.59478539e+11, -3.50342060e+10])

## Sparse matrices

Sparse matrices are often useful in numerical simulations dealing with large systems, if the problem can be described in matrix form where the matrices or vectors mostly contains zeros. Scipy has a good support for sparse matrices, with basic linear algebra operations (such as equation solving, eigenvalue calculations, etc).

There are many possible strategies for storing sparse matrices in an efficient way. Some of the most common are the so-called coordinate form (COO), list of list (LIL) form,  and compressed-sparse column CSC (and row, CSR). Each format has some advantanges and disadvantages. Most computational algorithms (equation solving, matrix-matrix multiplication, etc) can be efficiently implemented using CSR or CSC formats, but they are not so intuitive and not so easy to initialize. So often a sparse matrix is initially created in COO or LIL format (where we can efficiently add elements to the sparse matrix data), and then converted to CSC or CSR before used in real calcalations.

For more information about these sparse formats, see e.g. http://en.wikipedia.org/wiki/Sparse_matrix

When we create a sparse matrix we have to choose which format it should be stored in. For example, 

In [4]:
import scipy.sparse as sp

In [3]:
# dense matrix
M = np.array([[2,-1,0,0,0], [-1,2,-1,0,0], [0,-1,2,-1,0],[0,0,-1,2,-1], [0,0,0,-1,2]]); 
M

array([[ 2, -1,  0,  0,  0],
       [-1,  2, -1,  0,  0],
       [ 0, -1,  2, -1,  0],
       [ 0,  0, -1,  2, -1],
       [ 0,  0,  0, -1,  2]])

In [5]:
# convert from dense to sparse
A = sp.csr_matrix(M); 
#print(A)
print(A.indptr)
print(A.indices)
print(A.data)

[ 0  2  5  8 11 13]
[0 1 0 1 2 1 2 3 2 3 4 3 4]
[ 2 -1 -1  2 -1 -1  2 -1 -1  2 -1 -1  2]


In [ ]:
# convert from sparse to dense
A.todense()

matrix([[ 2, -1,  0,  0,  0],
        [-1,  2, -1,  0,  0],
        [ 0, -1,  2, -1,  0],
        [ 0,  0, -1,  2, -1],
        [ 0,  0,  0, -1,  2]], dtype=int64)

More efficient way to create sparse matrices: create an empty matrix and populate it using matrix indexing (avoids creating a potentially large dense matrix)

In [ ]:
A = sp.lil_matrix((4,4)) # empty 4x4 sparse matrix
A[0,0] = 1
A[1,1] = 3
A[2,2] = A[2,1] = 1
A[3,3] = A[3,0] = 1
A

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in List of Lists format>

In [ ]:
A.rows

array([list([0]), list([1]), list([1, 2]), list([0, 3])], dtype=object)

In [ ]:
A.todense()

Converting between different sparse matrix formats:

In [ ]:
A

In [ ]:
A = sp.csr_matrix(A); A

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
A = sp.csc_matrix(A); A

We can compute with sparse matrices like with dense matrices:

In [ ]:
A.todense()

In [ ]:
(A * A)

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
A.todense()

In [ ]:
A.dot(A)

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
v = np.array([1,2,3,4])[:,np.newaxis]; v

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
# sparse matrix - dense vector multiplication
A * v

array([[1.],
       [6.],
       [5.],
       [5.]])

In [ ]:
# same result with dense matrix - dense vector multiplcation
A.todense() * v

### Tridiagonal matrix solver

See a separate [notebook ](Laplacian1D.ipynb)

### Sparse solver

In [6]:
import numpy as np
from scipy import sparse
from scipy.sparse.linalg import spsolve
mtx = sparse.spdiags([[1, 2, 3, 4, 5], [6, 5, 8, 9, 10]], [0, 1], 5, 5)
print(mtx.todense())
mtx=mtx.tocsr()
#mtx=sparse.csr_matrix(mtx)
rhs = np.array([1, 2, 3, 4, 5], dtype=np.float32)

[[ 1  5  0  0  0]
 [ 0  2  8  0  0]
 [ 0  0  3  9  0]
 [ 0  0  0  4 10]
 [ 0  0  0  0  5]]


In [ ]:
help(spsolve)

In [ ]:
# solve as single precision real
mtx1 = mtx.astype(np.float32)
x = spsolve(mtx1, rhs, use_umfpack=True)
print(x)  

print("Error: %s" % (mtx1 * x - rhs))  

In [ ]:
# solve as double precision real
mtx2 = mtx.astype(np.float64)
x = spsolve(mtx2, rhs, use_umfpack=True)
print(x)  

print("Error: %s" % (mtx2 * x - rhs))  

In [ ]:
#solve as double precision complex
mtx2 = mtx.astype(np.complex128)
x = spsolve(mtx2, rhs, use_umfpack=True)
print(x)

print("Error: %s" % (mtx2 * x - rhs))   

### Iterative solvers

In [7]:
help(sparse.linalg)

Help on package scipy.sparse.linalg in scipy.sparse:

NAME
    scipy.sparse.linalg

DESCRIPTION
    Sparse linear algebra (:mod:`scipy.sparse.linalg`)
    
    .. currentmodule:: scipy.sparse.linalg
    
    Abstract linear operators
    -------------------------
    
    .. autosummary::
       :toctree: generated/
    
       LinearOperator -- abstract representation of a linear operator
       aslinearoperator -- convert an object to an abstract linear operator
    
    Matrix Operations
    -----------------
    
    .. autosummary::
       :toctree: generated/
    
       inv -- compute the sparse matrix inverse
       expm -- compute the sparse matrix exponential
       expm_multiply -- compute the product of a matrix exponential and a matrix
    
    Matrix norms
    ------------
    
    .. autosummary::
       :toctree: generated/
    
       norm -- Norm of a sparse matrix
       onenormest -- Estimate the 1-norm of a sparse matrix
    
    Solving linear problems
    -------

In [ ]:
help(sparse.linalg.bicgstab)

Help on function bicgstab in module scipy.sparse.linalg.isolve.iterative:

bicgstab(A, b, x0=None, tol=1e-05, maxiter=None, M=None, callback=None, atol=None)
    Use BIConjugate Gradient STABilized iteration to solve ``Ax = b``.
    
    Parameters
    ----------
    A : {sparse matrix, dense matrix, LinearOperator}
        The real or complex N-by-N matrix of the linear system.
        Alternatively, ``A`` can be a linear operator which can
        produce ``Ax`` using, e.g.,
        ``scipy.sparse.linalg.LinearOperator``.
    b : {array, matrix}
        Right hand side of the linear system. Has shape (N,) or (N,1).
    
    Returns
    -------
    x : {array, matrix}
        The converged solution.
    info : integer
        Provides convergence information:
            0  : successful exit
            >0 : convergence to tolerance not achieved, number of iterations
            <0 : illegal input or breakdown
    
    Other Parameters
    ----------------
    x0  : {array, matrix}
  

In [ ]:
print(mtx.todense())

[[ 1  5  0  0  0]
 [ 0  2  8  0  0]
 [ 0  0  3  9  0]
 [ 0  0  0  4 10]
 [ 0  0  0  0  5]]


In [8]:
x,info =sparse.linalg.bicgstab(mtx,rhs,tol=1e-10,maxiter=10)
x

array([106.00000002, -21.        ,   5.5       ,  -1.5       ,
         1.        ])

In [ ]:
info

0

### Read Matrix Market format

In [ ]:
import scipy.io as scio
import matplotlib.pyplot as plt
A=scio.mmread('mcfe.mtx')
type(A)

scipy.sparse.coo.coo_matrix

In [ ]:
plt.show(plt.spy())

TypeError: spy() missing 1 required positional argument: 'Z'

### Laplacian 2D

See a separate [notebook.](2DLaplaceFD.ipynb)