## Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

In [ ]:
import numpy as np

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [ ]:
v1 = np.arange(1, 4)
print(v1)
v2 = np.arange(3, 8)
print(v2)

[1 2 3]
[3 4 5 6 7]


In [ ]:
v1 * 2

array([2, 4, 6])

In [ ]:
v1 + 2

array([3, 4, 5])

In [ ]:
A = np.arange(0, 9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
A * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
A+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
A * A # element-wise multiplication

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
v1 * v1

If we multiply arrays with compatible shapes, we get an **element-wise** multiplication of each row:

In [ ]:
A.shape, v1.shape

((3, 3), (3,))

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
v1.shape

(3,)

In [ ]:
v1

array([1, 2, 3])

In [ ]:
A * v1

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

### Matrix algebra

#### Dot

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.dot(A, A)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [ ]:
np.dot(A, v1)

array([ 8, 26, 44])

In [ ]:
b=np.dot(v1, v1)
#type(b)
print(b)

14


#### Matrix type (deprecated)

Alternatively, we can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra. The use of `matrix` is deprecated.

In [ ]:
help(np.matrix)

Help on class matrix in module numpy:

class matrix(ndarray)
 |  matrix(data, dtype=None, copy=True)
 |  
 |  matrix(data, dtype=None, copy=True)
 |  
 |  .. note:: It is no longer recommended to use this class, even for linear
 |            algebra. Instead use regular arrays. The class may be removed
 |            in the future.
 |  
 |  Returns a matrix from an array-like object, or from a string of data.
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |  
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the 

In [ ]:
A

In [ ]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector
print(M)
print(v)

In [ ]:
M * M

In [ ]:
M * v

In [ ]:
# inner product
v.T * v

In [ ]:
# with matrix objects, standard matrix algebra applies
v + M*v

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [ ]:
v = np.matrix([1,2,3,4,5,6]).T
v

In [ ]:
np.shape(M), np.shape(v)

In [ ]:
M * v

#### Other commands

In [ ]:
help(np.cross)

Help on function cross in module numpy:

cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
    Return the cross product of two (arrays of) vectors.
    
    The cross product of `a` and `b` in :math:`R^3` is a vector perpendicular
    to both `a` and `b`.  If `a` and `b` are arrays of vectors, the vectors
    are defined by the last axis of `a` and `b` by default, and these axes
    can have dimensions 2 or 3.  Where the dimension of either `a` or `b` is
    2, the third component of the input vector is assumed to be zero and the
    cross product calculated accordingly.  In cases where both input vectors
    have dimension 2, the z-component of the cross product is returned.
    
    Parameters
    ----------
    a : array_like
        Components of the first vector(s).
    b : array_like
        Components of the second vector(s).
    axisa : int, optional
        Axis of `a` that defines the vector(s).  By default, the last axis.
    axisb : int, optional
        Axis of `b` that

In [ ]:
v3 = np.arange(0,3)
v4 = np.array([1,2,-1])
v5 = np.cross(v3,v4)
print(v5)

[-5  2 -1]


In [ ]:
np.dot(v3,v5)

0

In [ ]:
help(np.linalg.norm)

Help on function norm in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object.
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `x`
        is 1-D) or a matrix norm (when `x` is 2-D) i

In [ ]:
print(v3)
np.linalg.norm(v3,2)

[0 1 2]


2.23606797749979

In [ ]:
help(np.tensordot)

Help on function tensordot in module numpy:

tensordot(a, b, axes=2)
    Compute tensor dot product along specified axes.
    
    Given two tensors, `a` and `b`, and an array_like object containing
    two array_like objects, ``(a_axes, b_axes)``, sum the products of
    `a`'s and `b`'s elements (components) over the axes specified by
    ``a_axes`` and ``b_axes``. The third argument can be a single non-negative
    integer_like scalar, ``N``; if it is such, then the last ``N`` dimensions
    of `a` and the first ``N`` dimensions of `b` are summed over.
    
    Parameters
    ----------
    a, b : array_like
        Tensors to "dot".
    
    axes : int or (2,) array_like
        * integer_like
          If an int N, sum over the last N axes of `a` and the first N axes
          of `b` in order. The sizes of the corresponding axes must match.
        * (2,) array_like
          Or, a list of axes to be summed over, first sequence applying to `a`,
          second to `b`. Both element

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

### Array (and Matrix) transformations

Above we have used the `.T` to transpose the matrix object `v`. We could also have used the `transpose` function to accomplish the same thing. 

Other mathematical functions that transform matrix objects are:

In [ ]:
C = np.matrix([[1j, 2j], [3j, 4j]])  # deprecated
C

In [ ]:
C = np.array([[1j, 2j], [3j, 4j]])
C

array([[0.+1.j, 0.+2.j],
       [0.+3.j, 0.+4.j]])

In [ ]:
np.conjugate(C)

array([[0.-1.j, 0.-2.j],
       [0.-3.j, 0.-4.j]])

Hermitian conjugate: transpose + conjugate

We can extract the real and imaginary parts of complex-valued arrays using `real` and `imag`:

In [ ]:
np.real(C) # same as: C.real

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.imag(C) # same as: C.imag

array([[1., 2.],
       [3., 4.]])

Or the complex argument and absolute value

In [ ]:
np.angle(C+1) # Warning MATLAB Users, angle is used instead of arg

array([[0.78539816, 1.10714872],
       [1.24904577, 1.32581766]])

In [ ]:
np.abs(C)

array([[1., 2.],
       [3., 4.]])

### Matrix computations

#### Inverse

In [ ]:
C.I # if C is a matrix

In [ ]:
Cinv=np.linalg.inv(C) # equivalent to C.I 
Cinv

array([[0.+2.j , 0.-1.j ],
       [0.-1.5j, 0.+0.5j]])

In [ ]:
np.dot(Cinv,C)

array([[1.00000000e+00+0.j, 0.00000000e+00+0.j],
       [1.11022302e-16+0.j, 1.00000000e+00+0.j]])

In [ ]:
help(np.finfo)

Help on class finfo in module numpy:

class finfo(builtins.object)
 |  finfo(dtype)
 |  
 |  finfo(dtype)
 |  
 |  Machine limits for floating point types.
 |  
 |  Attributes
 |  ----------
 |  bits : int
 |      The number of bits occupied by the type.
 |  eps : float
 |      The smallest representable positive number such that
 |      ``1.0 + eps != 1.0``.  Type of `eps` is an appropriate floating
 |      point type.
 |  epsneg : floating point number of the appropriate type
 |      The smallest representable positive number such that
 |      ``1.0 - epsneg != 1.0``.
 |  iexp : int
 |      The number of bits in the exponent portion of the floating point
 |      representation.
 |  machar : MachAr
 |      The object which calculated these parameters and holds more
 |      detailed information.
 |  machep : int
 |      The exponent that yields `eps`.
 |  max : floating point number of the appropriate type
 |      The largest representable number.
 |  maxexp : int
 |      The smallest 

In [ ]:
print(np.finfo(float).eps)

#### Determinant

In [ ]:
np.linalg.det(C)

(2.0000000000000004+0j)

In [ ]:
np.linalg.det(Cinv)

(0.49999999999999967+0j)

### Solve linear system

To solve a linear system we can use the `linalg.solve` command which is a wrapper for the LAPACK routines `dgesv` and `zgesv`, the former being used if a is real-valued, the latter if it is complex-valued. The solution to the system of linear equations is computed using an LU decomposition with partial pivoting and row interchanges.

In [ ]:
help(np.linalg.solve)

Help on function solve in module numpy.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.
    
    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(..., M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.
    
    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is identical to `b`.
    
    Raises
    ------
    LinAlgError
        If `a` is singular or not square.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The solutions are computed using LAPACK routine ``_gesv``.
    
    `a` must be square and of full-rank, i.e., all rows (or, equivalently,
    columns) must be linearl

In [ ]:
A = np.array([[1,1], [1,2]])
b = np.array([2,3])
x = np.linalg.solve(A, b)
print(x)

[1. 1.]


In [ ]:
A = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = np.array([4,5,1])
x = np.linalg.solve(A, b)
print(x)

LinAlgError: Singular matrix

In [ ]:
np.linalg.det(A)

0.0

In [ ]:
help(np.linalg.cond)

Help on function cond in module numpy.linalg:

cond(x, p=None)
    Compute the condition number of a matrix.
    
    This function is capable of returning the condition number using
    one of seven different norms, depending on the value of `p` (see
    Parameters below).
    
    Parameters
    ----------
    x : (..., M, N) array_like
        The matrix whose condition number is sought.
    p : {None, 1, -1, 2, -2, inf, -inf, 'fro'}, optional
        Order of the norm:
    
        =====  ============================
        p      norm for matrices
        =====  ============================
        None   2-norm, computed directly using the ``SVD``
        'fro'  Frobenius norm
        inf    max(sum(abs(x), axis=1))
        -inf   min(sum(abs(x), axis=1))
        1      max(sum(abs(x), axis=0))
        -1     min(sum(abs(x), axis=0))
        2      2-norm (largest sing. value)
        -2     smallest singular value
        =====  ============================
    
        inf mea

In [ ]:
print(np.linalg.cond(A))

3.813147060626918e+16


**Exercise 1.** Write a Python function that takes two integer numbers `m` and `n` as input and creates the `m x n` Hilbert matrix. The Hilbert matrix has elements of the form `a[i,j]=1/(i+j-1)`. 

**Exercise 2.** Build a RHS vector for solving a linear system with the square Hilbert matrix of order `n` such that the solution is the vector of all 1. Solve the system for `n=5, 10, 100`.

**Exercise 3.** Build a RHS vector `b` for solving a linear system with the square Hilbert matrix (`H`) of order 5 such that the solution is the vector of all 1. Solve the system and get the solution `x`. Now perturb `b` with the vector `db=[0,0,0,0,1e-4]` and compute the new solution `x1`. Estimate the 2-norm condition number of `H` by means of 

\begin{equation}
\frac{\|x-x_1\|}{\|x\|}\leq \kappa_2 \frac{\|\delta b\|}{\|b\|}
\end{equation}

**Exercise 4.** Compute the condition number of the square Hilbert matrix for `n=5, 10, 100`.

### Eigenvalues and eigenvectors

Let A be an `n x n` matrix. The number &lambda; is an eigenvalue of `A` if there exists a non-zero vector `C` such that

Av = &lambda;v

In this case, vector `v` is called an eigenvector of `A` corresponding to &lambda;. You can use numpy to calculate the eigenvalues and eigenvectors of a matrix: 

In [ ]:
help(np.linalg.eig)

Help on function eig in module numpy.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.
    
    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed
    
    Returns
    -------
    w : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs
    
    v : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``v[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``w[i]``.
    
    Raises
    ------
    LinAlgError
        If the eigenvalue computation does not converg

In [ ]:
B = np.array([[-2, -4, 2],[-2, 1,2],[4,2,5]])
print(np.linalg.det(B))
l, v = np.linalg.eig(B)
print(l)
print(v)

-90.0
[-5.  3.  6.]
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]


**Exercise 1.** Take a look at the document available at __[www.cs.huji.ac.il/~csip/tirgul2.pdf](http://www.cs.huji.ac.il/~csip/tirgul2.pdf)__ describing the power method for calculating the largest eigenvalue of a matrix. Write a Python function that takes as input the matrix `A`, the initial guess of the eigenvector `x0` and the maximum number of iteration `itmax` and returns the maximum eigenvalue and the corresponding eigenvector.

**Exercise 2.** Implement the inverse power method. This method is the original method applied to the matrix $A^{-1}$. With reference to the solution of Exercise 1 it must be noticed that in this case the computation of `q` (lines 3 and 9) requires the solution of a linear system (to this aim use `np.linalg.solve`). 

**Exercise 3.** Implement the inverse power method with shift. This method is the original method applied to the matrix $(A-\lambda I)^{-1}$; the user has to supply $\lambda$ (the _shift_ ) and the algorithm will find the closest eigenvalue to $\lambda$.

### Data processing

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays. 

In [ ]:
help(np.random)

In [ ]:
data=np.random.rand(100,5)
data

#### mean

In [ ]:
# interesting data is in column 3
np.mean(data[:,3])

#### standard deviations and variance

In [ ]:
np.std(data[:,3]), np.var(data[:,3])

#### min and max

In [ ]:
# lowest value in column
data[:,3].min()

In [ ]:
# highest value in column
data[:,3].max()

In [ ]:
data1 = np.random.rand(5,3)
data1

In [ ]:
data1.min()

#### sum, prod, and trace

In [ ]:
d = np.arange(1, 6)
d

In [ ]:
# sum up all elements
sum(d)

In [ ]:
# product of all elements
np.prod(d)

In [ ]:
# cummulative sum
np.cumsum(d)

In [ ]:
# cummulative product
np.cumprod(d)

In [ ]:
A=np.random.rand(5,5)
# same as: diag(A).sum()
np.trace(A)

#### Vectorization

As mentioned several times by now, to get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [ ]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    #print(type(x))
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
Theta(-8)

0

In [ ]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

OK, that didn't work because we didn't write the `Theta` function so that it can handle a vector input... 

To get a vectorized version of Theta we can use the Numpy function `vectorize`. In many cases it can automatically vectorize a function:

In [ ]:
Theta_vec = np.vectorize(Theta)
Theta_vec

In [ ]:
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

In [ ]:
v = np.array([-3,-2,-1,0,1,2,3])
1.0*(v>=0)

array([0., 0., 0., 1., 1., 1., 1.])

We can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [ ]:
import numpy as np

In [ ]:
def Theta(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    #print(isinstance(x, np.ndarray))
    return 1 * (x >= 0)

In [ ]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

In [ ]:
# still works for scalars as well
Theta(-1.2), Theta(2.6)

(0, 1)