# SVD decomposition with `scipy`

Import the required modules

In [1]:
import scipy.linalg as la
import numpy as np

Generate a random 5x4 matrix

In [2]:
A = np.random.rand(5,4)
A

array([[0.52902229, 0.46502903, 0.58652354, 0.35140033],
       [0.82581306, 0.97520609, 0.1126152 , 0.26095724],
       [0.44528833, 0.29194349, 0.82532593, 0.96470703],
       [0.88688653, 0.23529412, 0.24321327, 0.17809052],
       [0.17334783, 0.47111925, 0.78251914, 0.00882002]])

## `<numpy|scipy>.linalg.svd` 

Equivalent implementations:
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html



### Full SVD (`full_matrices = True` - default)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times m}, S \in \mathbb{R}^{m\times n}, V \in \mathbb{R}^{n\times n}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.


In [11]:
U, s, VT = np.linalg.svd(A)
# U, s, VT = la.svd(A)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 5)
s shape:  (4,)
VT shape:  (4, 4)


but s is an array

In [9]:
s

array([2.21287439, 0.945967  , 0.62824165, 0.42846405])

Build the matrix $S$

In [10]:
S = np.zeros(A.shape)
for i in range(len(s)):
    S[i, i] = s[i]
S

array([[2.21287439, 0.        , 0.        , 0.        ],
       [0.        , 0.945967  , 0.        , 0.        ],
       [0.        , 0.        , 0.62824165, 0.        ],
       [0.        , 0.        , 0.        , 0.42846405],
       [0.        , 0.        , 0.        , 0.        ]])

In [5]:
S = la.diagsvd(s, A.shape[0], A.shape[1])
S

array([[2.52842492, 0.        , 0.        , 0.        ],
       [0.        , 0.72715521, 0.        , 0.        ],
       [0.        , 0.        , 0.28591845, 0.        ],
       [0.        , 0.        , 0.        , 0.21149482],
       [0.        , 0.        , 0.        , 0.        ]])

Reconstruct the matrix $A$

In [12]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))

err: 1.959858e-15


### Thin SVD (`full_matrices = False`)

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times q}, S \in \mathbb{R}^{q\times q}, V \in \mathbb{R}^{n\times q}$

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.



In [15]:
# del U, s, S, VT
U, s, VT = la.svd(A, full_matrices = False)
print('U shape: ', U.shape)
print('s shape: ', s.shape)
print('VT shape: ', VT.shape)

U shape:  (5, 4)
s shape:  (4,)
VT shape:  (4, 4)


Build the matrix $S$

In [16]:
S = np.diag(s)
S

array([[2.21287439, 0.        , 0.        , 0.        ],
       [0.        , 0.945967  , 0.        , 0.        ],
       [0.        , 0.        , 0.62824165, 0.        ],
       [0.        , 0.        , 0.        , 0.42846405]])

Reconstruct the matrix $A$

In [17]:
A_svd = np.matmul(U, np.matmul(S,VT))
print('err: %e' % (la.norm(A - A_svd) / la.norm(A)))

err: 1.959858e-15
